print("Welcome to class")
print("Hello")
print("Welcome to class")
print("Hello")
print("Welcome to class")
print("Hello")
print("Welcome to class")
print("Hello")
print("Welcome to class")
print("Hello")
print("Welcome to class")
print("Hello")
print("Welcome to class")
print("Hello")
